// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ledgerapp.djinni

#pragma once

#include <memory>
#include <string>
#include <vector>

namespace ledgerapp_gen {

class Http;
class ThreadDispatcher;
class TransactionListVmHandle;

class Api {
public:
    virtual ~Api() {}

    static std::shared_ptr<Api> create_api(const std::shared_ptr<Http> & http_impl, const std::shared_ptr<ThreadDispatcher> & thread_dispatcher);

    virtual std::shared_ptr<TransactionListVmHandle> observer_transaction_list() = 0;

    virtual std::vector<std::string> get_transactions(const std::string & address) = 0;
};

}  // namespace ledgerapp_gen
