// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include <cstdint>
#include <utility>

namespace ledgerapp_gen {

struct ApiOptions final {
    int32_t coin_type;

    ApiOptions(int32_t coin_type_)
    : coin_type(std::move(coin_type_))
    {}
};

}  // namespace ledgerapp_gen
