// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from async.djinni

#pragma once

#include <cstdint>
#include <memory>

namespace ledgerapp_gen {

class Runnable;

class ExecutionContext {
public:
    virtual ~ExecutionContext() {}

    virtual void execute(const std::shared_ptr<Runnable> & runnable) = 0;

    virtual void delay(const std::shared_ptr<Runnable> & runnable, int64_t millis) = 0;
};

}  // namespace ledgerapp_gen
