// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

namespace ledgerapp_gen {

struct Response;

class HandleResponse {
public:
    virtual ~HandleResponse() {}

    virtual void respond(const Response & result) = 0;
};

}  // namespace ledgerapp_gen
