// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#pragma once

#include <string>
#include <utility>

namespace ledgerapp_gen {

struct HttpHeader final {
    std::string field;
    std::string value;

    HttpHeader(std::string field_,
               std::string value_)
    : field(std::move(field_))
    , value(std::move(value_))
    {}
};

}  // namespace ledgerapp_gen
