// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#pragma once

#include "stl.hpp"
#include <memory>
#include <string>
#include <vector>

namespace ledgerapp_gen {

class HttpCallback;
struct HttpHeader;

class Http {
public:
    virtual ~Http() {}

    virtual void get(const std::string & url, const std::experimental::optional<std::vector<HttpHeader>> & header, const std::shared_ptr<HttpCallback> & callback) = 0;
};

}  // namespace ledgerapp_gen
