// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from async.djinni

#pragma once

namespace ledgerapp_gen {

class Runnable {
public:
    virtual ~Runnable() {}

    virtual void run() = 0;
};

}  // namespace ledgerapp_gen
