// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include <memory>

namespace ledgerapp_gen {

class TransactionListVm;

class TransactionListVmObserver {
public:
    virtual ~TransactionListVmObserver() {}

    virtual void on_update(const std::shared_ptr<TransactionListVm> & new_data) = 0;
};

}  // namespace ledgerapp_gen
