// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include <string>
#include <utility>

namespace ledgerapp_gen {

struct TransactionListVmCell final {
    std::string tx_hash;
    std::string received_at;
    std::string tx_data;

    TransactionListVmCell(std::string tx_hash_,
                          std::string received_at_,
                          std::string tx_data_)
    : tx_hash(std::move(tx_hash_))
    , received_at(std::move(received_at_))
    , tx_data(std::move(tx_data_))
    {}
};

}  // namespace ledgerapp_gen
