// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include <memory>
#include <string>
#include <vector>

namespace ledgerapp_gen {

class TransactionListVmObserver;

class TransactionListVmHandle {
public:
    virtual ~TransactionListVmHandle() {}

    virtual void start(const std::shared_ptr<TransactionListVmObserver> & observer, const std::vector<std::string> & addresses, bool testnetMode) = 0;

    virtual void stop() = 0;
};

}  // namespace ledgerapp_gen
